# Generated by Django 2.2.7 on 2019-12-31 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentInfo',
            fields=[
                ('exp_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('exp_magagername', models.CharField(max_length=12)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('exp_description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'experiment_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NisUserInfo',
            fields=[
                ('userid', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'nis_user_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubsysInfo',
            fields=[
                ('subsys_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'subsys_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_data', models.FloatField(blank=True, null=True)),
                ('data_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'test',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VDataMonitor',
            fields=[
                ('subsys_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('register_id', models.PositiveSmallIntegerField()),
                ('exp_id', models.PositiveSmallIntegerField()),
                ('v_data', models.FloatField()),
                ('v_data_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'v_data_monitor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VFormonitoring',
            fields=[
                ('subsys_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('register_id', models.PositiveSmallIntegerField()),
                ('ip_port', models.CharField(max_length=100)),
                ('v_register', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'v_formonitoring',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VInfoRegister',
            fields=[
                ('subsys_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('register_id', models.PositiveSmallIntegerField()),
                ('v_name', models.CharField(max_length=100)),
                ('ip_port', models.CharField(max_length=100)),
                ('created_time', models.DateTimeField()),
                ('created_manager', models.CharField(max_length=16)),
                ('v_type', models.CharField(max_length=20)),
                ('v_description', models.CharField(max_length=300)),
                ('v_status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'v_info_register',
                'managed': False,
            },
        ),
    ]
