# Generated by Django 2.2.7 on 2019-12-31 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='test222base',
            fields=[
                ('subsys_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'testdainfo',
                'managed': False,
            },
        ),
    ]
