# Generated by Django 2.2.7 on 2019-12-31 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_test222base'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test222base',
            options={},
        ),
    ]
