# Generated by Django 2.2.6 on 2019-10-30 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20191030_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentInfo',
            fields=[
                ('exp_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('exp_magagername', models.CharField(max_length=12)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('exp_description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'experiment_info',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Experiment_Info',
        ),
    ]
