# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'process_manager.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(687, 618)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(0, 20, 651, 61))
        self.groupBox.setObjectName("groupBox")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(530, 20, 41, 21))
        self.label_6.setObjectName("label_6")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 20, 121, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.spinBox = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox.setGeometry(QtCore.QRect(460, 30, 42, 21))
        self.spinBox.setObjectName("spinBox")
        self.pushButton_15 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_15.setGeometry(QtCore.QRect(310, 20, 121, 31))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_4.setGeometry(QtCore.QRect(160, 20, 121, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(580, 20, 21, 21))
        self.label_7.setObjectName("label_7")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 80, 651, 491))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 360, 591, 101))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(40, 20, 101, 16))
        self.label_8.setObjectName("label_8")
        self.pushButton_17 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_17.setGeometry(QtCore.QRect(30, 50, 131, 31))
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_18.setGeometry(QtCore.QRect(160, 10, 30, 30))
        self.pushButton_18.setStyleSheet("border-radius:15px;\n"
"background-color:grey;\n"
"")
        self.pushButton_18.setText("")
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_19.setGeometry(QtCore.QRect(200, 50, 131, 31))
        self.pushButton_19.setObjectName("pushButton_19")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(240, 10, 41, 21))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(290, 10, 21, 21))
        self.label_12.setObjectName("label_12")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 10, 611, 161))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setGeometry(QtCore.QRect(290, 20, 30, 30))
        self.pushButton.setStyleSheet("border-radius:15px;\n"
"background-color:grey;\n"
"")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_5.setGeometry(QtCore.QRect(190, 60, 121, 31))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_12.setGeometry(QtCore.QRect(370, 60, 141, 31))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_6.setGeometry(QtCore.QRect(190, 100, 121, 31))
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(30, 30, 91, 16))
        self.label_3.setObjectName("label_3")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_7.setGeometry(QtCore.QRect(130, 20, 30, 30))
        self.pushButton_7.setStyleSheet("border-radius:15px;\n"
"background-color:grey;\n"
"")
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(180, 30, 101, 16))
        self.label.setObjectName("label")
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_13.setGeometry(QtCore.QRect(370, 100, 141, 31))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_8.setGeometry(QtCore.QRect(30, 60, 121, 31))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setGeometry(QtCore.QRect(480, 20, 30, 30))
        self.pushButton_2.setStyleSheet("border-radius:15px;\n"
"background-color:grey\n"
";\n"
"")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_9.setGeometry(QtCore.QRect(30, 100, 121, 31))
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(350, 30, 121, 16))
        self.label_2.setObjectName("label_2")
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(540, 30, 41, 21))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setGeometry(QtCore.QRect(590, 30, 21, 21))
        self.label_14.setObjectName("label_14")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 180, 601, 161))
        self.groupBox_5.setObjectName("groupBox_5")
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_10.setGeometry(QtCore.QRect(290, 20, 30, 30))
        self.pushButton_10.setStyleSheet("border-radius:15px;\n"
"background-color:grey;\n"
"")
        self.pushButton_10.setText("")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_11.setGeometry(QtCore.QRect(190, 60, 121, 31))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_14 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_14.setGeometry(QtCore.QRect(370, 60, 141, 31))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_34 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_34.setGeometry(QtCore.QRect(190, 100, 121, 31))
        self.pushButton_34.setObjectName("pushButton_34")
        self.label_4 = QtWidgets.QLabel(self.groupBox_5)
        self.label_4.setGeometry(QtCore.QRect(30, 30, 91, 16))
        self.label_4.setObjectName("label_4")
        self.pushButton_35 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_35.setGeometry(QtCore.QRect(130, 20, 30, 30))
        self.pushButton_35.setStyleSheet("border-radius:15px;\n"
"background-color:grey;\n"
"")
        self.pushButton_35.setText("")
        self.pushButton_35.setObjectName("pushButton_35")
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        self.label_5.setGeometry(QtCore.QRect(180, 30, 101, 16))
        self.label_5.setObjectName("label_5")
        self.pushButton_36 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_36.setGeometry(QtCore.QRect(370, 100, 141, 31))
        self.pushButton_36.setObjectName("pushButton_36")
        self.pushButton_37 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_37.setGeometry(QtCore.QRect(30, 60, 121, 31))
        self.pushButton_37.setObjectName("pushButton_37")
        self.pushButton_38 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_38.setGeometry(QtCore.QRect(480, 20, 30, 30))
        self.pushButton_38.setStyleSheet("border-radius:15px;\n"
"background-color:grey\n"
";\n"
"")
        self.pushButton_38.setText("")
        self.pushButton_38.setObjectName("pushButton_38")
        self.pushButton_39 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_39.setGeometry(QtCore.QRect(30, 100, 121, 31))
        self.pushButton_39.setObjectName("pushButton_39")
        self.label_20 = QtWidgets.QLabel(self.groupBox_5)
        self.label_20.setGeometry(QtCore.QRect(350, 30, 121, 16))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.groupBox_5)
        self.label_21.setGeometry(QtCore.QRect(540, 30, 41, 21))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.groupBox_5)
        self.label_22.setGeometry(QtCore.QRect(590, 30, 21, 21))
        self.label_22.setObjectName("label_22")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_7.setGeometry(QtCore.QRect(20, 190, 601, 161))
        self.groupBox_7.setObjectName("groupBox_7")
        self.pushButton_41 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_41.setGeometry(QtCore.QRect(30, 70, 121, 31))
        self.pushButton_41.setObjectName("pushButton_41")
        self.pushButton_43 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_43.setGeometry(QtCore.QRect(30, 110, 121, 31))
        self.pushButton_43.setObjectName("pushButton_43")
        self.label_24 = QtWidgets.QLabel(self.groupBox_7)
        self.label_24.setGeometry(QtCore.QRect(30, 30, 91, 16))
        self.label_24.setObjectName("label_24")
        self.pushButton_44 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_44.setGeometry(QtCore.QRect(130, 20, 30, 30))
        self.pushButton_44.setStyleSheet("border-radius:15px;\n"
"background-color:grey;\n"
"")
        self.pushButton_44.setText("")
        self.pushButton_44.setObjectName("pushButton_44")
        self.pushButton_47 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_47.setGeometry(QtCore.QRect(310, 20, 30, 30))
        self.pushButton_47.setStyleSheet("border-radius:15px;\n"
"background-color:grey\n"
";\n"
"")
        self.pushButton_47.setText("")
        self.pushButton_47.setObjectName("pushButton_47")
        self.label_26 = QtWidgets.QLabel(self.groupBox_7)
        self.label_26.setGeometry(QtCore.QRect(180, 30, 121, 16))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.groupBox_7)
        self.label_27.setGeometry(QtCore.QRect(370, 30, 41, 21))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.groupBox_7)
        self.label_28.setGeometry(QtCore.QRect(420, 30, 21, 21))
        self.label_28.setObjectName("label_28")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 20, 611, 161))
        self.groupBox_6.setObjectName("groupBox_6")
        self.pushButton_26 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_26.setGeometry(QtCore.QRect(30, 70, 121, 31))
        self.pushButton_26.setObjectName("pushButton_26")
        self.pushButton_28 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_28.setGeometry(QtCore.QRect(30, 110, 121, 31))
        self.pushButton_28.setObjectName("pushButton_28")
        self.label_10 = QtWidgets.QLabel(self.groupBox_6)
        self.label_10.setGeometry(QtCore.QRect(30, 30, 91, 16))
        self.label_10.setObjectName("label_10")
        self.pushButton_29 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_29.setGeometry(QtCore.QRect(130, 20, 30, 30))
        self.pushButton_29.setStyleSheet("border-radius:15px;\n"
"background-color:grey;\n"
"")
        self.pushButton_29.setText("")
        self.pushButton_29.setObjectName("pushButton_29")
        self.pushButton_32 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_32.setGeometry(QtCore.QRect(310, 20, 30, 30))
        self.pushButton_32.setStyleSheet("border-radius:15px;\n"
"background-color:grey\n"
";\n"
"")
        self.pushButton_32.setText("")
        self.pushButton_32.setObjectName("pushButton_32")
        self.label_18 = QtWidgets.QLabel(self.groupBox_6)
        self.label_18.setGeometry(QtCore.QRect(180, 30, 121, 16))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.groupBox_6)
        self.label_19.setGeometry(QtCore.QRect(370, 30, 41, 21))
        self.label_19.setObjectName("label_19")
        self.label_23 = QtWidgets.QLabel(self.groupBox_6)
        self.label_23.setGeometry(QtCore.QRect(420, 30, 21, 21))
        self.label_23.setObjectName("label_23")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setGeometry(QtCore.QRect(30, 370, 591, 101))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setGeometry(QtCore.QRect(40, 20, 101, 16))
        self.label_9.setObjectName("label_9")
        self.pushButton_22 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_22.setGeometry(QtCore.QRect(30, 50, 131, 31))
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_23 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_23.setGeometry(QtCore.QRect(160, 10, 30, 30))
        self.pushButton_23.setStyleSheet("border-radius:15px;\n"
"background-color:grey;\n"
"")
        self.pushButton_23.setText("")
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_24 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_24.setGeometry(QtCore.QRect(200, 50, 131, 31))
        self.pushButton_24.setObjectName("pushButton_24")
        self.label_15 = QtWidgets.QLabel(self.groupBox_4)
        self.label_15.setGeometry(QtCore.QRect(240, 10, 41, 21))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.groupBox_4)
        self.label_16.setGeometry(QtCore.QRect(290, 10, 21, 21))
        self.label_16.setObjectName("label_16")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.pushButton_21 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_21.setGeometry(QtCore.QRect(740, 40, 271, 31))
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_20 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_20.setGeometry(QtCore.QRect(740, 90, 271, 31))
        self.pushButton_20.setObjectName("pushButton_20")
        self.groupBox_14 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_14.setGeometry(QtCore.QRect(20, 20, 611, 71))
        self.groupBox_14.setObjectName("groupBox_14")
        self.label_55 = QtWidgets.QLabel(self.groupBox_14)
        self.label_55.setGeometry(QtCore.QRect(30, 30, 91, 16))
        self.label_55.setObjectName("label_55")
        self.pushButton_80 = QtWidgets.QPushButton(self.groupBox_14)
        self.pushButton_80.setGeometry(QtCore.QRect(130, 20, 30, 30))
        self.pushButton_80.setStyleSheet("border-radius:15px;\n"
"background-color:grey;\n"
"")
        self.pushButton_80.setText("")
        self.pushButton_80.setObjectName("pushButton_80")
        self.pushButton_81 = QtWidgets.QPushButton(self.groupBox_14)
        self.pushButton_81.setGeometry(QtCore.QRect(340, 20, 30, 30))
        self.pushButton_81.setStyleSheet("border-radius:15px;\n"
"background-color:grey\n"
";\n"
"")
        self.pushButton_81.setText("")
        self.pushButton_81.setObjectName("pushButton_81")
        self.label_57 = QtWidgets.QLabel(self.groupBox_14)
        self.label_57.setGeometry(QtCore.QRect(210, 30, 121, 16))
        self.label_57.setObjectName("label_57")
        self.label_58 = QtWidgets.QLabel(self.groupBox_14)
        self.label_58.setGeometry(QtCore.QRect(400, 30, 41, 21))
        self.label_58.setObjectName("label_58")
        self.label_59 = QtWidgets.QLabel(self.groupBox_14)
        self.label_59.setGeometry(QtCore.QRect(470, 30, 21, 21))
        self.label_59.setObjectName("label_59")
        self.groupBox_15 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_15.setGeometry(QtCore.QRect(20, 110, 601, 71))
        self.groupBox_15.setObjectName("groupBox_15")
        self.label_60 = QtWidgets.QLabel(self.groupBox_15)
        self.label_60.setGeometry(QtCore.QRect(30, 30, 91, 16))
        self.label_60.setObjectName("label_60")
        self.pushButton_85 = QtWidgets.QPushButton(self.groupBox_15)
        self.pushButton_85.setGeometry(QtCore.QRect(130, 20, 30, 30))
        self.pushButton_85.setStyleSheet("border-radius:15px;\n"
"background-color:grey;\n"
"")
        self.pushButton_85.setText("")
        self.pushButton_85.setObjectName("pushButton_85")
        self.pushButton_86 = QtWidgets.QPushButton(self.groupBox_15)
        self.pushButton_86.setGeometry(QtCore.QRect(340, 20, 30, 30))
        self.pushButton_86.setStyleSheet("border-radius:15px;\n"
"background-color:grey\n"
";\n"
"")
        self.pushButton_86.setText("")
        self.pushButton_86.setObjectName("pushButton_86")
        self.label_62 = QtWidgets.QLabel(self.groupBox_15)
        self.label_62.setGeometry(QtCore.QRect(210, 30, 121, 16))
        self.label_62.setObjectName("label_62")
        self.label_63 = QtWidgets.QLabel(self.groupBox_15)
        self.label_63.setGeometry(QtCore.QRect(400, 30, 41, 21))
        self.label_63.setObjectName("label_63")
        self.label_64 = QtWidgets.QLabel(self.groupBox_15)
        self.label_64.setGeometry(QtCore.QRect(480, 30, 21, 21))
        self.label_64.setObjectName("label_64")
        self.groupBox_16 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_16.setGeometry(QtCore.QRect(20, 200, 621, 71))
        self.groupBox_16.setObjectName("groupBox_16")
        self.label_65 = QtWidgets.QLabel(self.groupBox_16)
        self.label_65.setGeometry(QtCore.QRect(40, 20, 101, 16))
        self.label_65.setObjectName("label_65")
        self.pushButton_88 = QtWidgets.QPushButton(self.groupBox_16)
        self.pushButton_88.setGeometry(QtCore.QRect(160, 10, 30, 30))
        self.pushButton_88.setStyleSheet("border-radius:15px;\n"
"background-color:grey;\n"
"")
        self.pushButton_88.setText("")
        self.pushButton_88.setObjectName("pushButton_88")
        self.label_66 = QtWidgets.QLabel(self.groupBox_16)
        self.label_66.setGeometry(QtCore.QRect(240, 10, 41, 21))
        self.label_66.setObjectName("label_66")
        self.label_67 = QtWidgets.QLabel(self.groupBox_16)
        self.label_67.setGeometry(QtCore.QRect(290, 10, 21, 21))
        self.label_67.setObjectName("label_67")
        self.tabWidget.addTab(self.tab_3, "")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(280, 580, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "Manager BOX"))
        self.label_6.setText(_translate("Dialog", "Exp_id"))
        self.pushButton_3.setText(_translate("Dialog", "Start Monitoring"))
        self.pushButton_15.setText(_translate("Dialog", "Set experiment id"))
        self.pushButton_4.setText(_translate("Dialog", "Stop Monitoring"))
        self.label_7.setText(_translate("Dialog", "0"))
        self.groupBox_3.setTitle(_translate("Dialog", "Parameter Read"))
        self.label_8.setText(_translate("Dialog", "Para Red process"))
        self.pushButton_17.setText(_translate("Dialog", "Run pararead"))
        self.pushButton_19.setText(_translate("Dialog", "Stop pararead"))
        self.label_11.setText(_translate("Dialog", "Exp_id"))
        self.label_12.setText(_translate("Dialog", "0"))
        self.groupBox_2.setTitle(_translate("Dialog", "PGPower"))
        self.pushButton_5.setText(_translate("Dialog", "Start Udp receive"))
        self.pushButton_12.setText(_translate("Dialog", "Run Datasave Thread"))
        self.pushButton_6.setText(_translate("Dialog", "Stop Udp receive"))
        self.label_3.setText(_translate("Dialog", "11_Udp_Thread"))
        self.label.setText(_translate("Dialog", "11_Udp_Reveiving"))
        self.pushButton_13.setText(_translate("Dialog", "Stop Datasave Thread"))
        self.pushButton_8.setText(_translate("Dialog", "Run Udp Thread"))
        self.pushButton_9.setText(_translate("Dialog", "Stop Udp Thread"))
        self.label_2.setText(_translate("Dialog", "11_Datasae_Thread"))
        self.label_13.setText(_translate("Dialog", "Exp_id"))
        self.label_14.setText(_translate("Dialog", "0"))
        self.groupBox_5.setTitle(_translate("Dialog", "Water Cool Down"))
        self.pushButton_11.setText(_translate("Dialog", "Start Udp receive"))
        self.pushButton_14.setText(_translate("Dialog", "Run Datasave Thread"))
        self.pushButton_34.setText(_translate("Dialog", "Stop Udp receive"))
        self.label_4.setText(_translate("Dialog", "02_Udp_Thread"))
        self.label_5.setText(_translate("Dialog", "02_Udp_Reveiving"))
        self.pushButton_36.setText(_translate("Dialog", "Stop Datasave Thread"))
        self.pushButton_37.setText(_translate("Dialog", "Run Udp Thread"))
        self.pushButton_39.setText(_translate("Dialog", "Stop Udp Thread"))
        self.label_20.setText(_translate("Dialog", "02_Process_Reveiving"))
        self.label_21.setText(_translate("Dialog", "Exp_id"))
        self.label_22.setText(_translate("Dialog", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Debug Mode"))
        self.groupBox_7.setTitle(_translate("Dialog", "Water Cool Down"))
        self.pushButton_41.setText(_translate("Dialog", "Start Udp Thread"))
        self.pushButton_43.setText(_translate("Dialog", "Stop Udp Thread"))
        self.label_24.setText(_translate("Dialog", "02_Udp_Thread"))
        self.label_26.setText(_translate("Dialog", "02_Process_Reveiving"))
        self.label_27.setText(_translate("Dialog", "Exp_id"))
        self.label_28.setText(_translate("Dialog", "0"))
        self.groupBox_6.setTitle(_translate("Dialog", "PGPower"))
        self.pushButton_26.setText(_translate("Dialog", "Run Udp Thread"))
        self.pushButton_28.setText(_translate("Dialog", "Stop Udp Thread"))
        self.label_10.setText(_translate("Dialog", "11_Udp_Thread"))
        self.label_18.setText(_translate("Dialog", "11_Datasae_Thread"))
        self.label_19.setText(_translate("Dialog", "Exp_id"))
        self.label_23.setText(_translate("Dialog", "0"))
        self.groupBox_4.setTitle(_translate("Dialog", "Parameter Read"))
        self.label_9.setText(_translate("Dialog", "Para Red process"))
        self.pushButton_22.setText(_translate("Dialog", "Run pararead"))
        self.pushButton_24.setText(_translate("Dialog", "Stop pararead"))
        self.label_15.setText(_translate("Dialog", "Exp_id"))
        self.label_16.setText(_translate("Dialog", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Menu Mode"))
        self.pushButton_21.setText(_translate("Dialog", "Stop  AutoProgrambyepics"))
        self.pushButton_20.setText(_translate("Dialog", "Start  AutoProgrambyepics"))
        self.groupBox_14.setTitle(_translate("Dialog", "PGPower"))
        self.label_55.setText(_translate("Dialog", "11_Udp_Thread"))
        self.label_57.setText(_translate("Dialog", "11_Datasae_Thread"))
        self.label_58.setText(_translate("Dialog", "Exp_id"))
        self.label_59.setText(_translate("Dialog", "0"))
        self.groupBox_15.setTitle(_translate("Dialog", "Water Cool Down"))
        self.label_60.setText(_translate("Dialog", "02_Udp_Thread"))
        self.label_62.setText(_translate("Dialog", "02_Process_Reveiving"))
        self.label_63.setText(_translate("Dialog", "Exp_id"))
        self.label_64.setText(_translate("Dialog", "0"))
        self.groupBox_16.setTitle(_translate("Dialog", "Parameter Read"))
        self.label_65.setText(_translate("Dialog", "Para Red process"))
        self.label_66.setText(_translate("Dialog", "Exp_id"))
        self.label_67.setText(_translate("Dialog", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Auto Mode"))
