# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guifile.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1474, 845)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(920, 670, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 421, 641))
        self.groupBox.setObjectName("groupBox")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(260, 40, 141, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(68, 40, 171, 25))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 100, 201, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 160, 201, 17))
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(20, 230, 201, 17))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(20, 300, 201, 17))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(20, 370, 201, 17))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(20, 450, 201, 17))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(20, 520, 201, 17))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(20, 580, 201, 17))
        self.label_10.setObjectName("label_10")
        self.D_02_Run = QtWidgets.QPushButton(self.groupBox)
        self.D_02_Run.setGeometry(QtCore.QRect(220, 90, 89, 25))
        self.D_02_Run.setObjectName("D_02_Run")
        self.D_02_Stop = QtWidgets.QPushButton(self.groupBox)
        self.D_02_Stop.setGeometry(QtCore.QRect(320, 90, 89, 25))
        self.D_02_Stop.setObjectName("D_02_Stop")
        self.D_04_Run = QtWidgets.QPushButton(self.groupBox)
        self.D_04_Run.setGeometry(QtCore.QRect(220, 160, 89, 25))
        self.D_04_Run.setObjectName("D_04_Run")
        self.D_04_Stop = QtWidgets.QPushButton(self.groupBox)
        self.D_04_Stop.setGeometry(QtCore.QRect(320, 160, 89, 25))
        self.D_04_Stop.setObjectName("D_04_Stop")
        self.D_05_Run = QtWidgets.QPushButton(self.groupBox)
        self.D_05_Run.setGeometry(QtCore.QRect(220, 230, 89, 25))
        self.D_05_Run.setObjectName("D_05_Run")
        self.D_05_Stop = QtWidgets.QPushButton(self.groupBox)
        self.D_05_Stop.setGeometry(QtCore.QRect(320, 230, 89, 25))
        self.D_05_Stop.setObjectName("D_05_Stop")
        self.D_06_Run = QtWidgets.QPushButton(self.groupBox)
        self.D_06_Run.setGeometry(QtCore.QRect(220, 290, 89, 25))
        self.D_06_Run.setObjectName("D_06_Run")
        self.D_06_Stop = QtWidgets.QPushButton(self.groupBox)
        self.D_06_Stop.setGeometry(QtCore.QRect(320, 290, 89, 25))
        self.D_06_Stop.setObjectName("D_06_Stop")
        self.D_07_Run = QtWidgets.QPushButton(self.groupBox)
        self.D_07_Run.setGeometry(QtCore.QRect(220, 360, 89, 25))
        self.D_07_Run.setObjectName("D_07_Run")
        self.D_07_Stop = QtWidgets.QPushButton(self.groupBox)
        self.D_07_Stop.setGeometry(QtCore.QRect(320, 360, 89, 25))
        self.D_07_Stop.setObjectName("D_07_Stop")
        self.D_08_Run = QtWidgets.QPushButton(self.groupBox)
        self.D_08_Run.setGeometry(QtCore.QRect(220, 450, 89, 25))
        self.D_08_Run.setObjectName("D_08_Run")
        self.D_08_Stop = QtWidgets.QPushButton(self.groupBox)
        self.D_08_Stop.setGeometry(QtCore.QRect(320, 450, 89, 25))
        self.D_08_Stop.setObjectName("D_08_Stop")
        self.D_10_Run = QtWidgets.QPushButton(self.groupBox)
        self.D_10_Run.setGeometry(QtCore.QRect(220, 520, 89, 25))
        self.D_10_Run.setObjectName("D_10_Run")
        self.D_10_Stop = QtWidgets.QPushButton(self.groupBox)
        self.D_10_Stop.setGeometry(QtCore.QRect(320, 520, 89, 25))
        self.D_10_Stop.setObjectName("D_10_Stop")
        self.D_11_Run = QtWidgets.QPushButton(self.groupBox)
        self.D_11_Run.setGeometry(QtCore.QRect(220, 570, 89, 25))
        self.D_11_Run.setObjectName("D_11_Run")
        self.D_11_Stop = QtWidgets.QPushButton(self.groupBox)
        self.D_11_Stop.setGeometry(QtCore.QRect(320, 570, 89, 25))
        self.D_11_Stop.setObjectName("D_11_Stop")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(420, 0, 411, 641))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton_21 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_21.setGeometry(QtCore.QRect(260, 40, 141, 25))
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_22.setGeometry(QtCore.QRect(68, 40, 171, 25))
        self.pushButton_22.setObjectName("pushButton_22")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(20, 100, 201, 17))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(20, 160, 201, 17))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(20, 230, 201, 17))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setGeometry(QtCore.QRect(20, 300, 201, 17))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setGeometry(QtCore.QRect(20, 370, 201, 17))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setGeometry(QtCore.QRect(20, 450, 201, 17))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setGeometry(QtCore.QRect(20, 520, 201, 17))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        self.label_18.setGeometry(QtCore.QRect(20, 580, 201, 17))
        self.label_18.setObjectName("label_18")
        self.T_02_Run = QtWidgets.QPushButton(self.groupBox_2)
        self.T_02_Run.setGeometry(QtCore.QRect(220, 90, 89, 25))
        self.T_02_Run.setObjectName("T_02_Run")
        self.T_02_Stop = QtWidgets.QPushButton(self.groupBox_2)
        self.T_02_Stop.setGeometry(QtCore.QRect(320, 90, 89, 25))
        self.T_02_Stop.setObjectName("T_02_Stop")
        self.T_04_Run = QtWidgets.QPushButton(self.groupBox_2)
        self.T_04_Run.setGeometry(QtCore.QRect(220, 160, 89, 25))
        self.T_04_Run.setObjectName("T_04_Run")
        self.T_04_Stop = QtWidgets.QPushButton(self.groupBox_2)
        self.T_04_Stop.setGeometry(QtCore.QRect(320, 160, 89, 25))
        self.T_04_Stop.setObjectName("T_04_Stop")
        self.T_05_Run = QtWidgets.QPushButton(self.groupBox_2)
        self.T_05_Run.setGeometry(QtCore.QRect(220, 230, 89, 25))
        self.T_05_Run.setObjectName("T_05_Run")
        self.T_05_Stop = QtWidgets.QPushButton(self.groupBox_2)
        self.T_05_Stop.setGeometry(QtCore.QRect(320, 230, 89, 25))
        self.T_05_Stop.setObjectName("T_05_Stop")
        self.T_06_Run = QtWidgets.QPushButton(self.groupBox_2)
        self.T_06_Run.setGeometry(QtCore.QRect(220, 290, 89, 25))
        self.T_06_Run.setObjectName("T_06_Run")
        self.T_06_Stop = QtWidgets.QPushButton(self.groupBox_2)
        self.T_06_Stop.setGeometry(QtCore.QRect(320, 290, 89, 25))
        self.T_06_Stop.setObjectName("T_06_Stop")
        self.T_07_Run = QtWidgets.QPushButton(self.groupBox_2)
        self.T_07_Run.setGeometry(QtCore.QRect(220, 360, 89, 25))
        self.T_07_Run.setObjectName("T_07_Run")
        self.T_07_Stop = QtWidgets.QPushButton(self.groupBox_2)
        self.T_07_Stop.setGeometry(QtCore.QRect(320, 360, 89, 25))
        self.T_07_Stop.setObjectName("T_07_Stop")
        self.T_08_Run = QtWidgets.QPushButton(self.groupBox_2)
        self.T_08_Run.setGeometry(QtCore.QRect(220, 450, 89, 25))
        self.T_08_Run.setObjectName("T_08_Run")
        self.T_08_Stop = QtWidgets.QPushButton(self.groupBox_2)
        self.T_08_Stop.setGeometry(QtCore.QRect(320, 450, 89, 25))
        self.T_08_Stop.setObjectName("T_08_Stop")
        self.T_10_Run = QtWidgets.QPushButton(self.groupBox_2)
        self.T_10_Run.setGeometry(QtCore.QRect(220, 520, 89, 25))
        self.T_10_Run.setObjectName("T_10_Run")
        self.T_10_Stop = QtWidgets.QPushButton(self.groupBox_2)
        self.T_10_Stop.setGeometry(QtCore.QRect(320, 520, 89, 25))
        self.T_10_Stop.setObjectName("T_10_Stop")
        self.T_11_Run = QtWidgets.QPushButton(self.groupBox_2)
        self.T_11_Run.setGeometry(QtCore.QRect(220, 570, 89, 25))
        self.T_11_Run.setObjectName("T_11_Run")
        self.T_11_Stop = QtWidgets.QPushButton(self.groupBox_2)
        self.T_11_Stop.setGeometry(QtCore.QRect(320, 570, 89, 25))
        self.T_11_Stop.setObjectName("T_11_Stop")
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(830, 0, 411, 641))
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton_39 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_39.setGeometry(QtCore.QRect(260, 40, 141, 25))
        self.pushButton_39.setObjectName("pushButton_39")
        self.pushButton_40 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_40.setGeometry(QtCore.QRect(68, 40, 171, 25))
        self.pushButton_40.setObjectName("pushButton_40")
        self.label_19 = QtWidgets.QLabel(self.groupBox_3)
        self.label_19.setGeometry(QtCore.QRect(20, 100, 201, 17))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.groupBox_3)
        self.label_20.setGeometry(QtCore.QRect(20, 160, 201, 17))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.groupBox_3)
        self.label_21.setGeometry(QtCore.QRect(20, 230, 201, 17))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.groupBox_3)
        self.label_22.setGeometry(QtCore.QRect(20, 300, 201, 17))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.groupBox_3)
        self.label_23.setGeometry(QtCore.QRect(20, 370, 201, 17))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.groupBox_3)
        self.label_24.setGeometry(QtCore.QRect(20, 450, 201, 17))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.groupBox_3)
        self.label_25.setGeometry(QtCore.QRect(20, 520, 201, 17))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.groupBox_3)
        self.label_26.setGeometry(QtCore.QRect(20, 580, 201, 17))
        self.label_26.setObjectName("label_26")
        self.P_02_Run = QtWidgets.QPushButton(self.groupBox_3)
        self.P_02_Run.setGeometry(QtCore.QRect(220, 90, 89, 25))
        self.P_02_Run.setObjectName("P_02_Run")
        self.P_02_Stop = QtWidgets.QPushButton(self.groupBox_3)
        self.P_02_Stop.setGeometry(QtCore.QRect(320, 90, 89, 25))
        self.P_02_Stop.setObjectName("P_02_Stop")
        self.P_04_Run = QtWidgets.QPushButton(self.groupBox_3)
        self.P_04_Run.setGeometry(QtCore.QRect(220, 160, 89, 25))
        self.P_04_Run.setObjectName("P_04_Run")
        self.P_04_Stop = QtWidgets.QPushButton(self.groupBox_3)
        self.P_04_Stop.setGeometry(QtCore.QRect(320, 160, 89, 25))
        self.P_04_Stop.setObjectName("P_04_Stop")
        self.P_05_Run = QtWidgets.QPushButton(self.groupBox_3)
        self.P_05_Run.setGeometry(QtCore.QRect(220, 230, 89, 25))
        self.P_05_Run.setObjectName("P_05_Run")
        self.P_05_Stop = QtWidgets.QPushButton(self.groupBox_3)
        self.P_05_Stop.setGeometry(QtCore.QRect(320, 230, 89, 25))
        self.P_05_Stop.setObjectName("P_05_Stop")
        self.P_06_Run = QtWidgets.QPushButton(self.groupBox_3)
        self.P_06_Run.setGeometry(QtCore.QRect(220, 290, 89, 25))
        self.P_06_Run.setObjectName("P_06_Run")
        self.P_06_Stop = QtWidgets.QPushButton(self.groupBox_3)
        self.P_06_Stop.setGeometry(QtCore.QRect(320, 290, 89, 25))
        self.P_06_Stop.setObjectName("P_06_Stop")
        self.P_07_Run = QtWidgets.QPushButton(self.groupBox_3)
        self.P_07_Run.setGeometry(QtCore.QRect(220, 360, 89, 25))
        self.P_07_Run.setObjectName("P_07_Run")
        self.P_07_Stop = QtWidgets.QPushButton(self.groupBox_3)
        self.P_07_Stop.setGeometry(QtCore.QRect(310, 360, 89, 25))
        self.P_07_Stop.setObjectName("P_07_Stop")
        self.P_08_Run = QtWidgets.QPushButton(self.groupBox_3)
        self.P_08_Run.setGeometry(QtCore.QRect(220, 450, 89, 25))
        self.P_08_Run.setObjectName("P_08_Run")
        self.P_08_Stop = QtWidgets.QPushButton(self.groupBox_3)
        self.P_08_Stop.setGeometry(QtCore.QRect(320, 450, 89, 25))
        self.P_08_Stop.setObjectName("P_08_Stop")
        self.P_10_Run = QtWidgets.QPushButton(self.groupBox_3)
        self.P_10_Run.setGeometry(QtCore.QRect(220, 520, 89, 25))
        self.P_10_Run.setObjectName("P_10_Run")
        self.P_10_Stop = QtWidgets.QPushButton(self.groupBox_3)
        self.P_10_Stop.setGeometry(QtCore.QRect(320, 520, 89, 25))
        self.P_10_Stop.setObjectName("P_10_Stop")
        self.P_11_Run = QtWidgets.QPushButton(self.groupBox_3)
        self.P_11_Run.setGeometry(QtCore.QRect(220, 570, 89, 25))
        self.P_11_Run.setObjectName("P_11_Run")
        self.P_11_Stop = QtWidgets.QPushButton(self.groupBox_3)
        self.P_11_Stop.setGeometry(QtCore.QRect(320, 570, 89, 25))
        self.P_11_Stop.setObjectName("P_11_Stop")
        self.databasecheck = QtWidgets.QPushButton(Dialog)
        self.databasecheck.setGeometry(QtCore.QRect(100, 640, 141, 111))
        self.databasecheck.setObjectName("databasecheck")
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(250, 640, 241, 192))
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "Down computer Simulatiion"))
        self.pushButton_2.setText(_translate("Dialog", "停止"))
        self.pushButton.setText(_translate("Dialog", "运行"))
        self.label.setText(_translate("Dialog", "02--watercoolwown_num10"))
        self.label_2.setText(_translate("Dialog", "04--Ceium_num2"))
        self.label_5.setText(_translate("Dialog", "05--GasControl_num3"))
        self.label_6.setText(_translate("Dialog", "06--PG_Magnetic_num2"))
        self.label_7.setText(_translate("Dialog", "07--Filament_num4"))
        self.label_8.setText(_translate("Dialog", "08--RFpower_num1"))
        self.label_9.setText(_translate("Dialog", "10--leadingoutpower_num2"))
        self.label_10.setText(_translate("Dialog", "11--acceleratpower_num2"))
        self.D_02_Run.setText(_translate("Dialog", "D_02_Run"))
        self.D_02_Stop.setText(_translate("Dialog", "D_02_Stop"))
        self.D_04_Run.setText(_translate("Dialog", "D_04_Run"))
        self.D_04_Stop.setText(_translate("Dialog", "D_04_Stop"))
        self.D_05_Run.setText(_translate("Dialog", "D_05_Run"))
        self.D_05_Stop.setText(_translate("Dialog", "D_05_Stop"))
        self.D_06_Run.setText(_translate("Dialog", "D_06_Run"))
        self.D_06_Stop.setText(_translate("Dialog", "D_06_Stop"))
        self.D_07_Run.setText(_translate("Dialog", "D_07_Run"))
        self.D_07_Stop.setText(_translate("Dialog", "D_07_Stop"))
        self.D_08_Run.setText(_translate("Dialog", "D_08_Run"))
        self.D_08_Stop.setText(_translate("Dialog", "D_08_Stop"))
        self.D_10_Run.setText(_translate("Dialog", "D_10_Run"))
        self.D_10_Stop.setText(_translate("Dialog", "D_10_Stop"))
        self.D_11_Run.setText(_translate("Dialog", "D_11_Run"))
        self.D_11_Stop.setText(_translate("Dialog", "D_11_Stop"))
        self.groupBox_2.setTitle(_translate("Dialog", "TCP Receive"))
        self.pushButton_21.setText(_translate("Dialog", "停止"))
        self.pushButton_22.setText(_translate("Dialog", "运行"))
        self.label_11.setText(_translate("Dialog", "02--watercoolwown_num10"))
        self.label_12.setText(_translate("Dialog", "04--Ceium_num2"))
        self.label_13.setText(_translate("Dialog", "05--GasControl_num3"))
        self.label_14.setText(_translate("Dialog", "06--PG_Magnetic_num2"))
        self.label_15.setText(_translate("Dialog", "07--Filament_num4"))
        self.label_16.setText(_translate("Dialog", "08--RFpower_num1"))
        self.label_17.setText(_translate("Dialog", "10--leadingoutpower_num2"))
        self.label_18.setText(_translate("Dialog", "11--acceleratpower_num2"))
        self.T_02_Run.setText(_translate("Dialog", "T_02_Run"))
        self.T_02_Stop.setText(_translate("Dialog", "T_02_Stop"))
        self.T_04_Run.setText(_translate("Dialog", "T_04_Run"))
        self.T_04_Stop.setText(_translate("Dialog", "T_04_Stop"))
        self.T_05_Run.setText(_translate("Dialog", "T_05_Run"))
        self.T_05_Stop.setText(_translate("Dialog", "T_05_Stop"))
        self.T_06_Run.setText(_translate("Dialog", "T_06_Run"))
        self.T_06_Stop.setText(_translate("Dialog", "T_06_Stop"))
        self.T_07_Run.setText(_translate("Dialog", "T_07_Run"))
        self.T_07_Stop.setText(_translate("Dialog", "T_07_Stop"))
        self.T_08_Run.setText(_translate("Dialog", "T_08_Run"))
        self.T_08_Stop.setText(_translate("Dialog", "T_08_Stop"))
        self.T_10_Run.setText(_translate("Dialog", "T_10_Run"))
        self.T_10_Stop.setText(_translate("Dialog", "T_10_Stop"))
        self.T_11_Run.setText(_translate("Dialog", "T_11_Run"))
        self.T_11_Stop.setText(_translate("Dialog", "T_11_Stop"))
        self.groupBox_3.setTitle(_translate("Dialog", "Process Data"))
        self.pushButton_39.setText(_translate("Dialog", "停止"))
        self.pushButton_40.setText(_translate("Dialog", "运行"))
        self.label_19.setText(_translate("Dialog", "02--watercoolwown_num10"))
        self.label_20.setText(_translate("Dialog", "04--Ceium_num2"))
        self.label_21.setText(_translate("Dialog", "05--GasControl_num3"))
        self.label_22.setText(_translate("Dialog", "06--PG_Magnetic_num2"))
        self.label_23.setText(_translate("Dialog", "07--Filament_num4"))
        self.label_24.setText(_translate("Dialog", "08--RFpower_num1"))
        self.label_25.setText(_translate("Dialog", "10--leadingoutpower_num2"))
        self.label_26.setText(_translate("Dialog", "11--acceleratpower_num2"))
        self.P_02_Run.setText(_translate("Dialog", "P_02_Run"))
        self.P_02_Stop.setText(_translate("Dialog", "P_02_Stop"))
        self.P_04_Run.setText(_translate("Dialog", "P_04_Run"))
        self.P_04_Stop.setText(_translate("Dialog", "P_04_Stop"))
        self.P_05_Run.setText(_translate("Dialog", "P_05_Run"))
        self.P_05_Stop.setText(_translate("Dialog", "P_05_Stop"))
        self.P_06_Run.setText(_translate("Dialog", "P_06_Run"))
        self.P_06_Stop.setText(_translate("Dialog", "P_06_Stop"))
        self.P_07_Run.setText(_translate("Dialog", "P_07_Run"))
        self.P_07_Stop.setText(_translate("Dialog", "P_07_Stop"))
        self.P_08_Run.setText(_translate("Dialog", "P_08_Run"))
        self.P_08_Stop.setText(_translate("Dialog", "P_08_Stop"))
        self.P_10_Run.setText(_translate("Dialog", "P_10_Run"))
        self.P_10_Stop.setText(_translate("Dialog", "P_10_Stop"))
        self.P_11_Run.setText(_translate("Dialog", "P_11_Run"))
        self.P_11_Stop.setText(_translate("Dialog", "P_08_Stop"))
        self.databasecheck.setText(_translate("Dialog", "Database check"))
